### ISSUE TITLE
Transparence des feuilles

### ISSUE THREAD

**Issue by Phoenix3838** [mindstorm38/proc-gen#4]
Les faces arrières des blocs de feuille ne sont pas affichés.
On peut ainsi le voir sur la face haute (image 1), sur le côté (image 2), et sur la face basse (image 3).

![bug4a](https://user-images.githubusercontent.com/59746148/72183426-49b43000-33ee-11ea-8e87-7664ffbd02f6.jpg)
![bug4b](https://user-images.githubusercontent.com/59746148/72183427-4a4cc680-33ee-11ea-9d30-f3c3ea6946d9.jpg)
![bug4c](https://user-images.githubusercontent.com/59746148/72183429-4a4cc680-33ee-11ea-9894-390fed8ff603.jpg)

**Comment by theorzr** [comment]
Serait-ce une bonne idée d'afficher ces faces ?
Dans le sens où cela ferait peut-être trop de faces visible à l'œil et cela serait peut-être désagréable (forêts trop denses) ?

Qu'en penses-tu ?

**Comment by Phoenix3838** [comment]
En effet, dans Minecraft, ces faces ne sont pas affichées. Cela m'est apparu comme un bug car je joue avec les graphismes au minimum, et les feuilles sont donc opaques.
Je pense que ce n'est donc pas un bug et que cette issue peut être clôturé.
